[destination.postgres.credentials]
database = "smartup" # fill this in!
password = "golibjon"# fill this in!
username = "postgres" # fill this in!
host = "localhost" # fill this in!
port = 5432
connect_timeout = 15
