[destination.postgres.credentials]
database = "db" # fill this in!
password = "password"# fill this in!
username = "postgres" # fill this in!
host = "host" # fill this in!
port = 5432
connect_timeout = 15
