[destination.postgres.credentials]
database = "postgres" # fill this in!
password = "golibjon0694946 "# fill this in!
username = "postgres" # fill this in!
host = "db.miahtcmsiqveqmiodxze.supabase.co" # fill this in!
port = 5432
connect_timeout = 15
